images:
  image:
    repository: ghcr.io/bigdestiny2/p2p-hiverelay
    tag: 0.26.0-rc.5
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  blindspark_container_name: blindspark
  perms_container_name: permissions
  run_as_user: 999
  run_as_group: 999
  default_api_port: 9100
