import '../../packages/blind-client-public-browser/test/browser-artifact.test.js'
import '../../packages/blind-client-public-browser/test/browser-artifact-inbox.test.js'
import '../../packages/blind-client-public-browser/test/cell-get-browser-artifact.test.js'
import '../../packages/blind-client-public-browser/test/cell-get-control.test.js'
import '../../packages/blind-client-public-browser/test/http-control.test.js'
